name: Publish multi-platform Docker image

on:
  release:
    types: [published]

env:
  CONTAINER_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: newman
  DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ${{ env.CONTAINER_REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata for Docker (tags, labels, annotations)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.CONTAINER_REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}
            ${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}
          labels: org.opencontainers.image.title=${{ env.DOCKER_IMAGE_NAME }}
          annotations: org.opencontainers.image.title=${{ env.DOCKER_IMAGE_NAME }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:test

      - name: Test Docker image
        run: docker run --rm ${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:test --version

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: false # https://github.com/orgs/community/discussions/45969
